### ISSUE TITLE
Question/Issue - Dependency on resources for using formatting methods

### ISSUE THREAD

**Issue by mdgbayly** [BrightspaceUI/localize-behavior#12]
This is more of an FYI for now, as I plan to dig into how we can use this component to dynamically load resources which will also affect this question/issue.

I was trying out switching over to this component to utilize some of its date/time formatting helpers.
I ran into an issue where calling formatDateTime as the app was loading was using an empty language. This is mostly because we load our resources dynamically (using another instantiation of app-localize-behavior) so at the point where we call formatDateTime, the resources are not yet loaded. Probably I could work around that by making our use of formatDateTime depend on the resources too.

But it struck me that maybe the formatting functions shouldn't depend on the resources being available. For lang terms, I can see why it makes sense to make the selected lang depend on the availability of resources, but not sure the same holds true for using the formatting functions, particularly if someone wants to use the formatting helpers in a component where there are no lang terms.

Also need to get my head around how we can use this component's lang detection capabilities when dynamically loading resources from an external file, as that becomes a bit chicken and egg (was hoping to switch to this component for lang term translation too but using external files).  Maybe we need to try to load lang, fallback lang and 'en' external files.  We use the ifrau lang builder utilities to copy base resources into each locale file, but currently our use of app-localize assumes that the preferred lang exists.

**Comment by dlockhart** [comment]
@mdgbayly I just put in some fixes that might address the issues you're having here. Check out the latest version!

**Comment by dlockhart** [comment]
Hopefully resolved -- please re-open in `@brightspace-ui/core` if not.
